# Generated by Django 3.0.6 on 2020-06-04 21:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='store_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=100)),
                ('link_store_website', models.CharField(max_length=300)),
                ('adress', models.CharField(max_length=200)),
                ('zip_code', models.CharField(max_length=40)),
                ('blurb_about_store', models.CharField(max_length=400)),
                ('verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='store_promotion_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion_title', models.CharField(max_length=100)),
                ('promotion_discription', models.CharField(max_length=400)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.store_user')),
            ],
        ),
        migrations.CreateModel(
            name='store_event_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=100)),
                ('event_time', models.CharField(max_length=100)),
                ('event_format', models.CharField(max_length=100)),
                ('event_discription', models.CharField(max_length=400)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.store_user')),
            ],
        ),
    ]
