# Generated by Django 3.0.6 on 2020-06-04 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('store', '0003_auto_20200604_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='follow_store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.UserProfile')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.store_user')),
            ],
        ),
    ]
