# Generated by Django 3.0.6 on 2020-06-05 14:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_follow_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='store_event_post',
            name='event_date',
            field=models.DateField(default=datetime.datetime(2020, 6, 5, 14, 51, 44, 241873, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store_event_post',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='store_promotion_post',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
